### ISSUE TITLE
crash when trying to put openlights on my server

### ISSUE THREAD

**Issue by nightstalker6669** [PC-Logix/OpenLights#4]
http://pastebin.com/nPt6tZQq

forge 1481

**Comment by nightstalker6669** [comment]
nvm just noticed this isn't updated to 1.7.10, could you possibly update it?

**Comment by CaitlynMainer** [comment]
Umm, OpenLights is totally updated to 1.7, the default branch here on GitHub is 1.6 but it's not the actively deved branch.  Also this isn't my crash, you're missing a library: "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/common/Configuration"

**Comment by CaitlynMainer** [comment]
You're running the 1.6.4 version of OpenLights, http://minecraft.curseforge.com/mc-mods/225225-openlights/files  get the 1.7.10 version.
